@host = localhost
@port = 3000
@resource=users
@token=123.123.123

### GET all users
GET http://{{host}}:{{port}}/{{resource}}/

### GET a user by id
GET http://{{host}}:{{port}}/{{resource}}/5305a5cf-3442-40f9-849b-6d8e2bca8317

### GET users by query name
GET http://{{host}}:{{port}}/{{resource}}?name=HenrY

### GET users by query lastname
GET http://{{host}}:{{port}}/{{resource}}?lastname=garzon

### GET users by query name and lastname
GET http://{{host}}:{{port}}/{{resource}}?name=henRy&lastname=Cordoba

### POST a new user
POST http://{{host}}:{{port}}/{{resource}}/register
Content-Type: application/json

{
  "sql": "SELECT (name, cel, email) FROM user WHERE id=5fe99f3c-cb58-4ab5-afb0-0f81eaca197f",
  "id": "550e8400-e29b-41d4-a716-446655440023",
  "name": "henry",
  "lastname": "Ochoa",
  "email": "henry@agmail.commerm",
  "password": "12232",
  "birthdate": "2000-12-31",
  "photo": ""
}

### PATCH a user exited
PATCH http://{{host}}:{{port}}/{{resource}}/5305a5cf-3442-40f9-849b-6d8e2bca8317
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Henry",
  "lastname": "Ochoa Garzón",
  "password": "   ",
  "cel": "",
  "birthdate": "",
  "photo": ""
}

### DELETE a user exited
DELETE http://{{host}}:{{port}}/{{resource}}/13567d7f-b1ca-4198-a0ec-e02df4a1f59a
Authorization: Bearer {{token}}